name: Deploy to Netlify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Replace Telegram Secrets
        run: |
          sed -i "s/__BOT_TOKEN__/${{ secrets.TELEGRAM_BOT_TOKEN }}/g" assets/js/main.js
          sed -i "s/__CHAT_ID__/${{ secrets.TELEGRAM_CHAT_ID }}/g" assets/js/main.js
          
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: '.'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
